//! M72 acceptance criterion 1: `spex build <recipe.json> -o <out.ldr>`
//! writes a real `.ldr` that `spex-ldraw`'s own `parse_scene` reads back
//! without error, and that `spex mesh-model` renders. Black-box (spawns the
//! built binary), the same pattern `schema_validation.rs` already uses.
//!
//! Needs a populated `.ldraw-cache/` (the real parts `spex build`'s test
//! recipes place — 3005.dat, 3004.dat — plus their real subpart tree) to
//! run offline; falls back to a live fetch otherwise. `#[ignore]`d for the
//! same reason `spex-ldraw`'s own network-dependent tests are: this is a
//! real, not synthetic, check, so it is not part of the default fast loop.
use spex_ldraw::{parse_scene, LdrawCache, ModelSource};
use std::path::{Path, PathBuf};
use std::process::Command;

fn spex_bin() -> &'static str {
    env!("CARGO_BIN_EXE_spex")
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

#[test]
#[ignore = "needs a populated .ldraw-cache/ (or network on a cold cache) to actually resolve real part geometry"]
fn a_real_recipe_builds_parses_and_renders() {
    let dir = std::env::temp_dir().join(format!("spex-build-roundtrip-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();

    let recipe = repo_root().join("recipes/test/wall-and-column.json");
    let ldr = dir.join("wall-and-column.ldr");
    let cache_dir = repo_root().join(".ldraw-cache");

    let status = Command::new(spex_bin())
        .arg("build")
        .arg(&recipe)
        .arg("-o")
        .arg(&ldr)
        .status()
        .expect("running spex build");
    assert!(status.success(), "spex build failed");
    assert!(ldr.exists(), "spex build did not write {}", ldr.display());

    // parse_scene reads it back with no error (acceptance criterion 1).
    let cache = LdrawCache::new(&cache_dir);
    let scene = parse_scene(&cache, ModelSource::LocalFile(&ldr)).unwrap_or_else(|e| panic!("parse_scene on spex-build's own output: {e}"));
    assert_eq!(scene.placements.len(), 37, "the wall-and-column fixture's own real placement count");
    assert!(scene.source_author.unwrap_or_default().contains("machine-generated by spex-build"));

    // spex mesh-model renders it without error.
    let bundle_dir = dir.join("mesh");
    let status = Command::new(spex_bin())
        .arg("mesh-model")
        .arg(&ldr)
        .arg("-o")
        .arg(&bundle_dir)
        .arg("--cache-dir")
        .arg(&cache_dir)
        .status()
        .expect("running spex mesh-model");
    assert!(status.success(), "spex mesh-model failed to render spex-build's own output");
    assert!(bundle_dir.join("mesh.json").exists());

    let _ = std::fs::remove_dir_all(&dir);
}
