//! M67 — `FugueSpec`: the plan, not the score.
//!
//! # What this is and what it is not
//!
//! Rev 4 of the spec deleted a format. There used to be a `fugue.json` that
//! was the runtime score and a `.mid` export that nobody loaded; there is now
//! one score — **a standard MIDI file, generated by M68, loaded by the
//! browser, openable in any DAW** — and this, which is the *input* to that
//! generator.
//!
//! So `FugueSpec` carries the decisions a person makes: the mode, the tempo,
//! the subject, the countersubject, and the bar-by-bar plan of where entries
//! and episodes fall. It carries no notes beyond the two authored lines. M68
//! fills in everything else and emits the SMF.
//!
//! `spec/fugue.schema.json` describes this object as it appears inside
//! `show.json`'s `audio` field, and `crates/spex-show`'s own schema test
//! validates the real Act I document against it.
//!
//! # The subject is authored, and this is the file it is authored in
//!
//! Everything else in this project is generated from data or derived from a
//! rule. The subject is not, and the spec says so: *"this is the one musical
//! decision the piece does not delegate to an algorithm."* It is written out
//! below as a constant, in scale degrees, with its letter names in the doc
//! comment so a musician can check it without running anything — which is
//! M67's third acceptance criterion.

use serde::{Deserialize, Serialize};

use crate::theory::{compass_steps, line_beats, Key, Line, Mode, Note};

/// The whole audio plan, as carried in `show.json`'s `audio` field.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FugueSpec {
    pub version: u32,
    /// Beats per minute of the canonical cut. **A longer cut does not slow
    /// the tempo** — it adds episodes and entries. The music is the same
    /// music, which is the same argument `resolve.rs` makes about the film.
    pub bpm: f64,
    pub meter: [u32; 2],
    pub mode: Key,
    pub voices: u32,
    /// The subject. Authored.
    pub subject: Line,
    /// The countersubject. **Required**, and required to be invertible — see
    /// `ACT_ONE_COUNTERSUBJECT`.
    pub countersubject: Line,
    /// Where entries, episodes and cadences fall, in bars.
    pub plan: Vec<Section>,
    pub pulse: PulseSpec,
}

/// One structural section of the fugue. The generator realises each into
/// notes; none of them may move off the bar it is given, because those bars
/// are the film's.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum Section {
    /// The four voices enter in turn, alternating subject and answer.
    Exposition { entries: Vec<Entry> },
    /// Free voices between entries. It **must modulate and must not introduce
    /// new material** — `target_degree` is where it lands, and `motif_from`
    /// says which existing material it sequences. An episode that invents a
    /// tune is an interlude, and that is the fastest way for a generated
    /// fugue to stop sounding like one.
    Episode {
        bars: f64,
        #[serde(rename = "atBar")]
        at_bar: f64,
        #[serde(rename = "sequenceInterval")]
        sequence_interval: i32,
        #[serde(rename = "motifFrom")]
        motif_from: MotifSource,
        /// The scale degree the episode ends in: the key of the entry that
        /// follows it.
        #[serde(rename = "targetDegree")]
        target_degree: i32,
    },
    /// A single later entry, possibly inverted or augmented.
    Entry {
        voice: u32,
        degree: i32,
        #[serde(rename = "atBar")]
        at_bar: f64,
        #[serde(default, skip_serializing_if = "std::ops::Not::not")]
        inversion: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        augmentation: Option<f64>,
    },
    /// Entries overlapping before the previous one has finished.
    Stretto {
        bars: f64,
        #[serde(rename = "atBar")]
        at_bar: f64,
        #[serde(rename = "overlapBeats")]
        overlap_beats: f64,
        voices: Vec<u32>,
    },
    /// A held note under everything else.
    Pedal {
        bars: f64,
        #[serde(rename = "atBar")]
        at_bar: f64,
        voice: u32,
        degree: i32,
    },
    Cadence {
        bars: f64,
        #[serde(rename = "atBar")]
        at_bar: f64,
        #[serde(rename = "type")]
        cadence_type: CadenceType,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum MotifSource {
    SubjectHead,
    CountersubjectTail,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CadenceType {
    Authentic,
    Plagal,
    Phrygian,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Entry {
    pub voice: u32,
    pub transposition: Transposition,
    #[serde(rename = "atBar")]
    pub at_bar: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Transposition {
    Tonic,
    Dominant,
}

/// The Act IV percussive layer.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct PulseSpec {
    #[serde(rename = "enterAtSec")]
    pub enter_at_sec: f64,
    #[serde(rename = "bpmMultiplier")]
    pub bpm_multiplier: f64,
    /// The Kick: one final accent, sample-aligned to the camera's.
    #[serde(rename = "finalAccentAtSec")]
    pub final_accent_at_sec: f64,
}

// ---------------------------------------------------------- the authored music

/// D Dorian. D4 = MIDI 62, and the mode of the oldest continuously notated
/// European repertoire — chosen for the archaeological register of Act I.
pub fn act_one_key() -> Key {
    Key::new(62, Mode::Dorian)
}

/// **The subject.** Two bars, eight beats, D Dorian.
///
/// ```text
///  beat  1     2     3    3½    4     5        7     8
///  note  A3    D4    G4   F4    E4    B4       A4    D4
///  deg   4/-1  0/0   3/0  2/0   1/0   5/0      4/0   0/0
///  len   1     1     ½    ½     1     2        1     1
/// ```
///
/// Letter names, for checking by eye: **A – D – G – F – E – B – A – D**.
///
/// # Three decisions, none of them arbitrary
///
/// **It opens on the dominant.** A3 is the fifth degree, a fourth below the
/// tonic, and it is there so that the answer has to be *tonal* — the head's
/// dominant is answered by the tonic, up a fourth, not up a fifth. That
/// distinction is the single thing that makes a fugue sound like a fugue
/// rather than like a canon, and a subject that never touches the dominant in
/// its head would never exercise it. See `theory::answer`.
///
/// **It carries 1 : 4 : 9.** The monolith's proportions are the piece's own
/// number, and they are in the subject three times over: it rests on the
/// **tonic** (1), it opens with a leap of a **fourth** (4), and its total
/// compass — lowest note to highest — is a **ninth** (9). Those are not
/// decorative claims; `the_subject_carries_the_monoliths_proportions` below
/// asserts each of them, so the subject cannot be edited into disagreeing
/// with the object it is about.
///
/// **It holds the sixth.** B natural is the one note that distinguishes D
/// Dorian from D minor, and it lands on the downbeat of bar 2 and is held for
/// two beats — the longest note in the subject, at its highest point. A mode
/// that is never heard is a mode that was not chosen.
pub fn act_one_subject() -> Line {
    vec![
        Note::new(4, -1, 1.0), // A3  — the dominant, below the tonic
        Note::new(0, 0, 1.0),  // D4  — up a fourth: the 4 of 1:4:9
        Note::new(3, 0, 0.5),  // G4
        Note::new(2, 0, 0.5),  // F4
        Note::new(1, 0, 1.0),  // E4
        Note::new(5, 0, 2.0),  // B4  — the Dorian sixth, held, on the downbeat
        Note::new(4, 0, 1.0),  // A4
        Note::new(0, 0, 1.0),  // D4  — home
    ]
}

/// **The countersubject.** Two beats of silence, then six steady crotchets.
///
/// ```text
///  beat  1     2     3     4     5     6     7     8
///  note  –     –     E4    C4    D4    G4    F4    B3
///  deg   rest  rest  1/0   6/-1  0/0   3/0   2/0   5/-1
/// ```
///
/// Letter names: **(rest) – E – C – D – G – F – B**.
///
/// # Why it starts on beat 3, and why that is not a stylistic choice
///
/// The first draft covered all eight beats and passed every check against the
/// subject. It failed against the **answer** — an unprepared second on beat 1
/// and a perfect fifth on beat 3 — and the reason is structural rather than
/// accidental:
///
/// > **A countersubject cannot cover the subject's head, because the head is
/// > precisely the part that is not the same in the answer.**
///
/// That is what a tonal answer *is*. This subject's first two notes move up a
/// fourth in the answer and up a fifth in the subject; any countersubject
/// written to fit one of those is guaranteed to fight the other. The
/// classical solution is the obvious one once seen — the voice that has just
/// finished the subject takes a breath, and the countersubject begins after
/// the head. It also happens to be what makes the second entry audible as an
/// entry, since the texture thins to one voice just before it arrives.
///
/// # It is invertible against both, and that is checked
///
/// Rev 4 made the countersubject mandatory *and* required invertible
/// counterpoint at the octave, which is not a stylistic preference: a fugue
/// exchanges its voices, and a countersubject that only works above the
/// subject collapses the first time the parts swap. The rule that decides it
/// is one line long — **no perfect fifths**, because a fifth inverts into a
/// fourth and a fourth against the bass is a dissonance — and
/// `theory::invertibility_faults` returns the beat of every violation rather
/// than a boolean.
///
/// The tests below check it against the subject *and* against the answer.
/// The answer is the one that matters first, because in the exposition the
/// countersubject is heard under the answer before it is ever heard under the
/// subject.
///
/// # Its rhythm is the subject's complement
///
/// Even crotchets, so it moves exactly where the subject holds: under the
/// two-beat B in bar 2 it supplies the only motion there is, and under the
/// subject's quavers in bar 1 it is silent. Two lines that move together are
/// one thicker line.
pub fn act_one_countersubject() -> Line {
    vec![
        Note::rest(1.0),       // the subject's head is not the answer's head
        Note::rest(1.0),
        Note::new(1, 0, 1.0),  // E4
        Note::new(6, -1, 1.0), // C4
        Note::new(0, 0, 1.0),  // D4
        Note::new(3, 0, 1.0),  // G4 — moving under the subject's held B
        Note::new(2, 0, 1.0),  // F4
        Note::new(5, -1, 1.0), // B3
    ]
}

/// Length of the subject in bars, at the document's own meter.
pub fn subject_bars(spec: &FugueSpec) -> f64 {
    line_beats(&spec.subject) / spec.meter[0] as f64
}

/// Structural facts about the authored subject, for the tests and for the
/// status block. Nothing here is a constant: every number is read off the
/// notes, so editing the subject changes the numbers rather than making the
/// documentation wrong.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SubjectFacts {
    pub beats: f64,
    /// Lowest to highest, in scale steps. 8 is a ninth.
    pub compass_steps: i32,
    /// The opening interval, in scale steps. 3 is a fourth.
    pub opening_leap_steps: i32,
    /// The degree the subject ends on.
    pub final_degree: i32,
    pub longest_note_beats: f64,
    pub longest_note_degree: i32,
}

pub fn subject_facts(subject: &[Note]) -> SubjectFacts {
    let longest = subject
        .iter()
        .max_by(|a, b| a.beats.partial_cmp(&b.beats).unwrap())
        .copied()
        .unwrap_or(Note::new(0, 0, 0.0));
    SubjectFacts {
        beats: line_beats(subject),
        compass_steps: compass_steps(subject),
        opening_leap_steps: subject.get(1).map_or(0, |n| n.step()) - subject[0].step(),
        final_degree: subject.last().map_or(0, |n| n.degree),
        longest_note_beats: longest.beats,
        longest_note_degree: longest.degree,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theory::{answer, answer_kind, invertibility_faults, parallel_perfects, AnswerKind};

    #[test]
    fn the_subject_is_two_bars_at_four_four() {
        assert_eq!(line_beats(&act_one_subject()), 8.0);
        assert_eq!(line_beats(&act_one_countersubject()), 8.0);
    }

    #[test]
    fn the_subject_carries_the_monoliths_proportions() {
        // 1 : 4 : 9, three times over. If someone edits the subject, this is
        // the test that says the piece stopped being about its own object.
        let f = subject_facts(&act_one_subject());
        assert_eq!(f.final_degree, 0, "1 — it rests on the tonic");
        assert_eq!(f.opening_leap_steps, 3, "4 — it opens with a leap of a fourth");
        assert_eq!(f.compass_steps, 8, "9 — its compass is a ninth");
    }

    #[test]
    fn the_subject_makes_the_mode_audible() {
        // The longest note is the Dorian sixth. In D Aeolian that note would
        // be B-flat, so this is the note that decides which mode anyone
        // actually hears.
        let f = subject_facts(&act_one_subject());
        assert_eq!(f.longest_note_degree, 5);
        assert_eq!(f.longest_note_beats, 2.0);
        let k = act_one_key();
        assert_eq!(k.spell(5, 0), "B4");
        assert_eq!(k.to_midi(5, 0) - k.to_midi(0, 0), 9, "a major sixth, not a minor one");
    }

    #[test]
    fn the_subject_spells_out_as_a_d_g_f_e_b_a_d() {
        // AC3: human-checkable without running the generator.
        let k = act_one_key();
        let names: Vec<String> =
            act_one_subject().iter().map(|n| k.spell(n.degree, n.octave)).collect();
        assert_eq!(names, vec!["A3", "D4", "G4", "F4", "E4", "B4", "A4", "D4"]);
    }

    #[test]
    fn the_countersubject_spells_out_as_e_c_d_g_f_b_after_two_rests() {
        let k = act_one_key();
        let cs = act_one_countersubject();
        assert_eq!(cs.iter().filter(|n| n.rest).count(), 2, "the head is left uncovered");
        assert_eq!(line_beats(&cs[..2]), 2.0);
        let names: Vec<String> = cs
            .iter()
            .filter(|n| !n.rest)
            .map(|n| k.spell(n.degree, n.octave))
            .collect();
        assert_eq!(names, vec!["E4", "C4", "D4", "G4", "F4", "B3"]);
    }

    #[test]
    fn the_subject_asks_for_a_tonal_answer_and_gets_one() {
        let s = act_one_subject();
        assert_eq!(answer_kind(&s, Mode::Dorian), AnswerKind::Tonal);
        let k = act_one_key();
        let a = answer(&s, Mode::Dorian);
        // A3 -> D4 (a fourth, because the head's dominant is answered by the
        // tonic), then D4 -> A4 (a fifth). Everything after is a plain fifth.
        assert_eq!(k.to_midi(a[0].degree, a[0].octave), 62);
        assert_eq!(k.to_midi(a[1].degree, a[1].octave), 69);
        assert_eq!(a[2].step() - s[2].step(), 4);
        // And a *real* answer would have opened a fifth up, on E4 — which is
        // the wrong note and the reason this distinction exists.
        let real = crate::theory::answer_with_head(&s, Mode::Dorian, AnswerKind::Real, 0);
        assert_eq!(k.to_midi(real[0].degree, real[0].octave), 64);
    }

    #[test]
    fn the_countersubject_is_invertible_at_the_octave() {
        // The claim in the doc comment, as an assertion. Not "looks fine".
        let faults =
            invertibility_faults(&act_one_subject(), &act_one_countersubject(), act_one_key());
        assert!(faults.is_empty(), "invertibility faults: {faults:?}");
    }

    #[test]
    fn subject_and_countersubject_have_no_parallel_fifths_or_octaves() {
        let p = parallel_perfects(&act_one_subject(), &act_one_countersubject(), act_one_key());
        assert!(p.is_empty(), "parallel perfect consonances at beats {p:?}");
    }

    #[test]
    fn the_countersubject_moves_where_the_subject_holds() {
        // The subject holds one note across beats 4 and 5 (its two-beat B).
        // The countersubject must not, or bar 2 has no motion in it at all.
        let s = act_one_subject();
        let cs = act_one_countersubject();
        let s4 = crate::theory::note_at(&s, 4.0).unwrap();
        let s5 = crate::theory::note_at(&s, 5.0).unwrap();
        assert_eq!(s4.step(), s5.step(), "the subject holds here");
        let c4 = crate::theory::note_at(&cs, 4.0).unwrap();
        let c5 = crate::theory::note_at(&cs, 5.0).unwrap();
        assert_ne!(c4.step(), c5.step(), "so the countersubject must move");
    }

    #[test]
    fn the_countersubject_is_invertible_against_the_answer_too() {
        // The exposition puts the countersubject under the *answer* before it
        // is ever under the subject, so this is the check that matters first —
        // and it is the one the first draft failed, which is how the two rests
        // got there. Both lines move up a fifth together; the answer's head
        // does not, which is the whole point and is why the rests cover it.
        let a = answer(&act_one_subject(), Mode::Dorian);
        let cs = crate::theory::transpose_steps(&act_one_countersubject(), 4);
        let faults = invertibility_faults(&a, &cs, act_one_key());
        assert!(faults.is_empty(), "against the answer: {faults:?}");
        let p = parallel_perfects(&a, &cs, act_one_key());
        assert!(p.is_empty(), "parallels against the answer at {p:?}");
    }

    #[test]
    fn inverting_the_pair_puts_the_countersubject_on_top_and_it_still_works() {
        // Double counterpoint, actually performed rather than asserted: put
        // the countersubject an octave above the subject instead of below it,
        // and the intervals must still be legal. This is the operation the
        // whole invertibility rule exists to protect.
        let s = act_one_subject();
        let cs_up = crate::theory::transpose_steps(&act_one_countersubject(), 7);
        let faults = invertibility_faults(&cs_up, &s, act_one_key());
        assert!(faults.is_empty(), "inverted: {faults:?}");
    }
}
