#!/usr/bin/env python3
"""Writes a synthetic large LDraw scene, for measuring the renderer rather
than for looking at.

M55's acceptance criteria need a scene with tens of thousands of instances.
The real one is the Atlas (M74), which is weeks away and gated on content
that does not exist yet; M59's own correction (B10) already established that
a week-6 milestone must not be gated on a week-17 deliverable. So: a
generator, right here, producing a real `.ldr` that goes through the exact
same `spex mesh-model` path every other scene does.

The output is deliberately *not* committed. It is 50 000 lines of nothing
anyone needs to read, and regenerating it is one command:

    python3 scripts/gen_stress_scene.py -o /tmp/stress-50k.ldr
    spex mesh-model /tmp/stress-50k.ldr -o /tmp/stress-50k-mesh

What it builds: a lattice of real 1x1 and 1x4 bricks in real LDraw colours,
on the real stud grid (20 LDU across, 24 LDU per brick course), so every
translation quantises exactly and the bundle reports 0.000 mm error — the
scene stresses instance *count*, and nothing else.
"""
import argparse

# Real LDraw part files, real LDraw colour codes.
PARTS = ["3005.dat", "3010.dat"]  # Brick 1 x 1, Brick 1 x 4
COLORS = [4, 14, 15, 0, 1, 2, 7]  # Red, Yellow, White, Black, Blue, Green, Light Grey

# Real LDraw geometry constants: one stud is 20 LDU across, one brick course
# is 24 LDU tall. Staying on this grid is what makes the i16 translation
# encoding exact rather than approximate.
STUD = 20
COURSE = 24

# The four axis-aligned orientations a brick can have on a stud grid. Kept
# small on purpose: the 10-byte instance record indexes orientations with a
# u8, and a stress scene should stress the instance count, not that table.
ORIENTATIONS = [
    (1, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0),
]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("-n", "--count", type=int, default=50_000)
    ap.add_argument("--footprint", type=int, default=64,
                    help="lattice width/depth in studs; height follows from count")
    args = ap.parse_args()

    w = args.footprint
    lines = [
        f"0 Synthetic stress lattice - {args.count} instances",
        "0 Name: stress.ldr",
        "0 Author: spex project (generated by scripts/gen_stress_scene.py)",
        "0 // NOT a model. A measurement fixture for M55's instanced renderer:",
        f"0 // a {w}x{w} lattice of real bricks on the real stud grid, stacked",
        "0 // until it reaches the requested instance count. Every translation",
        "0 // is a whole number of LDU, so the bundle's quantisation error is 0.",
        "0 BFC CERTIFY CCW",
    ]

    for i in range(args.count):
        x = i % w
        z = (i // w) % w
        y = i // (w * w)
        part = PARTS[(x + z) % len(PARTS)]
        color = COLORS[(x + y) % len(COLORS)]
        o = ORIENTATIONS[(x + z + y) % len(ORIENTATIONS)]
        # LDraw is Y-down, so stacking upward means going negative.
        tx, ty, tz = x * STUD * 4, -y * COURSE, z * STUD * 4
        lines.append(
            f"1 {color} {tx} {ty} {tz} " + " ".join(str(v) for v in o) + f" {part}"
        )

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.count} placements to {args.out}")


if __name__ == "__main__":
    main()
