//! Parametric solid generation for Ankerstein shapes — the real difference
//! from `spex-ldraw::geometry`, which resolves an existing LDraw mesh
//! instead. No equivalent open mesh library exists for Ankerstein (see
//! `docs/ANKERSTEIN-ENGINE.md` §1), so a shape's geometry is generated
//! directly from its `AnkersteinShape::dimensions_mm`, emitting the same
//! `spex_ldraw::geometry::Triangle` shape so `spex-ldraw`'s own
//! `sample_surface`/`shade_color`/`to_point_cloud` can be reused unchanged
//! (see this crate's `lib.rs` doc comment).
use crate::catalog::{AnkersteinShape, ShapeType};
use spex_ldraw::edges::{Edge, EdgeKind};
use spex_ldraw::geometry::{FullTriangle, PartGeometry, Triangle};
use spex_ldraw::LDU_TO_MM;

/// The 8 corners of a real axis-aligned box, centered at the origin, in the
/// exact order `generate_box`'s `FACES` table indexes into — shared by
/// `generate_box` (triangles) and `generate_box_edges` (the same box's real
/// edges) so the two can never drift apart: an edge always joins two
/// corners that a face actually uses.
fn box_corners(dimensions_mm: [f64; 3]) -> [[f64; 3]; 8] {
    let [w, h, d] = dimensions_mm.map(|v| v / 2.0);
    [
        [-w, -h, -d],
        [w, -h, -d],
        [w, h, -d],
        [-w, h, -d],
        [-w, -h, d],
        [w, -h, d],
        [w, h, d],
        [-w, h, d],
    ]
}

/// Generates a real axis-aligned rectangular box (a `ShapeType::Block`),
/// centered at the origin, with the exact `dimensions_mm` given —
/// straightforward analytic geometry (12 triangles, 2 per face), unlike
/// `spex-ldraw`'s recursive mesh resolution, since there's no file to
/// resolve.
pub fn generate_box(dimensions_mm: [f64; 3], color_code: u32) -> Vec<Triangle> {
    let corners = box_corners(dimensions_mm);
    // 6 faces, each as 2 triangles, CCW winding when viewed from outside.
    const FACES: [[usize; 4]; 6] = [
        [0, 1, 2, 3], // -Z
        [5, 4, 7, 6], // +Z
        [4, 0, 3, 7], // -X
        [1, 5, 6, 2], // +X
        [4, 5, 1, 0], // -Y
        [3, 2, 6, 7], // +Y
    ];
    let mut triangles = Vec::with_capacity(12);
    for face in FACES {
        let [a, b, c, e] = face.map(|i| corners[i]);
        triangles.push(Triangle { vertices: [a, b, c], color_code });
        triangles.push(Triangle { vertices: [a, c, e], color_code });
    }
    triangles
}

/// The real, exact 12 edges of a box generated by `generate_box` with the
/// same `dimensions_mm` — every one a hard, sharp edge (a rectangular box
/// has no curved surface, so nothing here needs the conditional-edge
/// silhouette test `spex-ldraw::edges` documents). Computed directly from
/// `box_corners`, the same corner data `generate_box` uses, rather than a
/// generic dihedral-angle detector: for an axis-aligned box every real edge
/// is already known analytically and exactly.
pub fn generate_box_edges(dimensions_mm: [f64; 3]) -> Vec<Edge> {
    let corners = box_corners(dimensions_mm);
    const EDGE_PAIRS: [(usize, usize); 12] = [
        // Bottom loop (y = -h).
        (0, 1),
        (1, 5),
        (5, 4),
        (4, 0),
        // Top loop (y = +h).
        (3, 2),
        (2, 6),
        (6, 7),
        (7, 3),
        // The 4 verticals joining the two loops.
        (0, 3),
        (1, 2),
        (5, 6),
        (4, 7),
    ];
    EDGE_PAIRS
        .iter()
        .map(|&(a, b)| Edge {
            vertices: [corners[a], corners[b]],
            color_code: None, // inherit the instance's own edge colour, same as LDraw code 24
            kind: EdgeKind::Hard,
            source: 0,
        })
        .collect()
}

/// Generates a real right-triangular prism (`ShapeType::Prism`) — the
/// simplest of the real historical "prism (sloped or triangular) shaped
/// blocks" from the fifth historical set (see this module's `Prism` match
/// arm in `generate_shape` for the real citation). Cross-section is a
/// right *isosceles* triangle (both legs equal to `leg_mm`, a 45° slope),
/// extruded `depth_mm` along the third axis, centered at the origin the
/// same way `generate_box` centers a block — **a real, deliberate scope
/// limit**: the historical record cites "six different roof slopes" in
/// total (see `docs/ANKERSTEIN-ENGINE.md` M99's own note), of which this
/// is only the one whose geometry is directly and simply citable (two
/// such prisms combine into a real cube); the other five angles are real
/// but not yet reduced to cited numbers, and would need their own
/// generation function (a different, non-isosceles cross-section) rather
/// than a parameter on this one.
///
/// Local layout before centering (right angle at the origin, legs along
/// +X/+Y, extrusion along +Z): cross-section vertices `(0,0)`, `(leg,0)`,
/// `(0,leg)`; two end caps plus three side faces (the two leg faces and
/// the sloped hypotenuse face) — 8 triangles total, each wound so its
/// face normal points outward (verified by `prism_faces_point_outward`
/// below, the same kind of check `spex-ldraw::geometry`'s BFC-CCW
/// assumption relies on for real LDraw parts).
/// The 6 corners of a real right-triangular prism (`[a0, b0, c0, a1, b1,
/// c1]` — the z=0 cap's 3 corners, then the z=d cap's 3, in the same order
/// `generate_prism` builds its triangles from), centered at the origin the
/// same way `generate_prism` centers its output. Shared by `generate_prism`
/// (triangles) and `generate_prism_edges` (the same prism's real edges).
fn prism_corners(leg_mm: f64, depth_mm: f64) -> [[f64; 3]; 6] {
    let l = leg_mm;
    let d = depth_mm;
    // Cross-section corners at z=0 and z=d, right angle at (0,0), before
    // centering.
    let mut corners = [
        [0.0, 0.0, 0.0],
        [l, 0.0, 0.0],
        [0.0, l, 0.0],
        [0.0, 0.0, d],
        [l, 0.0, d],
        [0.0, l, d],
    ];
    let offset = [-l / 2.0, -l / 2.0, -d / 2.0];
    for c in &mut corners {
        c[0] += offset[0];
        c[1] += offset[1];
        c[2] += offset[2];
    }
    corners
}

pub fn generate_prism(leg_mm: f64, depth_mm: f64, color_code: u32) -> Vec<Triangle> {
    let [a0, b0, c0, a1, b1, c1] = prism_corners(leg_mm, depth_mm);
    vec![
        // End caps.
        Triangle { vertices: [a0, c0, b0], color_code }, // z=0 cap, outward -Z
        Triangle { vertices: [a1, b1, c1], color_code }, // z=d cap, outward +Z
        // Leg face at y=0 (outward -Y).
        Triangle { vertices: [a0, b0, b1], color_code },
        Triangle { vertices: [a0, b1, a1], color_code },
        // Leg face at x=0 (outward -X).
        Triangle { vertices: [a0, c1, c0], color_code },
        Triangle { vertices: [a0, a1, c1], color_code },
        // Sloped hypotenuse face (outward, away from the right-angle edge).
        Triangle { vertices: [b0, c0, c1], color_code },
        Triangle { vertices: [b0, c1, b1], color_code },
    ]
}

/// The real, exact 9 edges of a right-triangular prism generated by
/// `generate_prism` with the same `leg_mm`/`depth_mm` — 3 per triangular
/// cap (including the sloped hypotenuse edge) plus 3 longitudinal edges
/// joining the two caps, all hard/sharp (no curved surface). Computed
/// directly from `prism_corners`, the same corner data `generate_prism`
/// uses.
pub fn generate_prism_edges(leg_mm: f64, depth_mm: f64) -> Vec<Edge> {
    let corners = prism_corners(leg_mm, depth_mm);
    const EDGE_PAIRS: [(usize, usize); 9] = [
        // z=0 cap triangle (a0, b0, c0).
        (0, 1),
        (1, 2),
        (2, 0),
        // z=d cap triangle (a1, b1, c1).
        (3, 4),
        (4, 5),
        (5, 3),
        // The 3 longitudinal edges joining the caps.
        (0, 3),
        (1, 4),
        (2, 5),
    ];
    EDGE_PAIRS
        .iter()
        .map(|&(a, b)| Edge {
            vertices: [corners[a], corners[b]],
            color_code: None,
            kind: EdgeKind::Hard,
            source: 0,
        })
        .collect()
}

/// Dispatches on a catalog shape's `shape_type`. `Block` (M98) and `Prism`
/// (M99) are implemented; `ArchVoussoir` (M101) is a real, planned next
/// step, not a silently unsupported placeholder.
pub fn generate_shape(shape: &AnkersteinShape, color_code: u32) -> anyhow::Result<Vec<Triangle>> {
    match shape.shape_type {
        ShapeType::Block => Ok(generate_box(shape.dimensions_mm, color_code)),
        ShapeType::Prism => {
            let [leg_x, leg_y, depth] = shape.dimensions_mm;
            if (leg_x - leg_y).abs() > 1e-9 {
                anyhow::bail!(
                    "shape {:?}: generate_prism only supports the real 45° isosceles case (equal X/Y legs) — \
                     got dimensions_mm {:?}; a non-isosceles roof slope needs its own generation function, \
                     see docs/ANKERSTEIN-ENGINE.md M99",
                    shape.id,
                    shape.dimensions_mm
                );
            }
            Ok(generate_prism(leg_x, depth, color_code))
        }
        ShapeType::ArchVoussoir => anyhow::bail!(
            "arch voussoir geometry not yet implemented (see docs/ANKERSTEIN-ENGINE.md M101) — shape {:?}",
            shape.id
        ),
    }
}

/// The real edges (see `generate_box_edges`/`generate_prism_edges`) for a
/// catalog shape — the edge counterpart of `generate_shape`'s dispatch over
/// triangles, same shape-type gating and same rejection for the
/// not-yet-implemented arch voussoir.
pub fn generate_shape_edges(shape: &AnkersteinShape) -> anyhow::Result<Vec<Edge>> {
    match shape.shape_type {
        ShapeType::Block => Ok(generate_box_edges(shape.dimensions_mm)),
        ShapeType::Prism => {
            let [leg_x, leg_y, depth] = shape.dimensions_mm;
            if (leg_x - leg_y).abs() > 1e-9 {
                anyhow::bail!(
                    "shape {:?}: generate_prism_edges only supports the real 45° isosceles case (equal X/Y legs) — \
                     got dimensions_mm {:?}",
                    shape.id,
                    shape.dimensions_mm
                );
            }
            Ok(generate_prism_edges(leg_x, depth))
        }
        ShapeType::ArchVoussoir => anyhow::bail!(
            "arch voussoir geometry not yet implemented (see docs/ANKERSTEIN-ENGINE.md M101) — shape {:?}",
            shape.id
        ),
    }
}

/// The exact mathematical inverse of `spex_mesh::bundle::to_output_position`
/// (scale by `LDU_TO_MM`, flip Y) — `1 / LDU_TO_MM`, flip Y back.
///
/// **Why this exists at all.** `spex_mesh::bundle::MeshBundleBuilder`'s
/// `add_part`/`add_instance` always run whatever geometry/translation they
/// are given through that fixed LDraw-specific conversion — it is baked
/// into those two methods, not something a caller can opt out of. Ankerstein
/// shapes (`generate_box`/`generate_prism`) are generated directly in real
/// millimetres, Y-up — exactly the frame that conversion *produces*, not
/// consumes (see `spex-cli/src/ankerstein.rs`'s doc comment for the same
/// LDraw-vs-Ankerstein frame mismatch on the point-cloud path). So
/// `to_part_geometry` below feeds the builder the precise inverse, making
/// the whole round trip a no-op: the mesh bundle's on-disk positions come
/// out as the real, unaltered millimetre coordinates `generate_box`/
/// `generate_prism` computed. `spex-cli`'s Ankerstein mesh-scene builder
/// reuses this same function for instance translations, which go through
/// an identical `to_output_position` conversion inside `add_instance`.
pub fn to_bundle_frame_position(p: [f64; 3]) -> [f64; 3] {
    let inv = 1.0 / LDU_TO_MM;
    [p[0] * inv, -p[1] * inv, p[2] * inv]
}

/// Converts a real catalog shape into a `spex_ldraw::geometry::PartGeometry`
/// — triangles from `generate_shape`, edges from `generate_shape_edges`,
/// both routed through `to_bundle_frame_position` so `MeshBundleBuilder::
/// add_part`'s internal LDraw-frame conversion reconstructs the real
/// millimetre geometry unchanged (see that function's doc comment).
///
/// The geometry itself carries no baked colour — every triangle/edge gets
/// `color_code: None` ("inherit"), exactly like a real LDraw part's
/// geometry — so one resolved shape can be instanced in any of
/// Ankerstein's three real colours without being resolved twice. The
/// `color_code` `generate_shape` itself takes is LDraw's own colour-16
/// ("inherit") placeholder, immediately discarded below; it exists only
/// because `Triangle` (unlike `FullTriangle`) always carries a concrete
/// colour.
pub fn to_part_geometry(shape: &AnkersteinShape) -> anyhow::Result<PartGeometry> {
    const INHERIT: u32 = 16;
    let triangles = generate_shape(shape, INHERIT)?;
    let edges = generate_shape_edges(shape)?;

    let full_triangles = triangles
        .iter()
        .map(|t| FullTriangle {
            // Matches `spex_mesh::bundle::to_output_triangles`'s own
            // vertex-swap convention: v1/v2 exchanged so the mirror this
            // frame conversion performs leaves the final winding correct.
            vertices: [
                to_bundle_frame_position(t.vertices[0]),
                to_bundle_frame_position(t.vertices[2]),
                to_bundle_frame_position(t.vertices[1]),
            ],
            color_code: None,
            source: 0,
        })
        .collect();

    let full_edges = edges
        .into_iter()
        .map(|e| Edge {
            vertices: [to_bundle_frame_position(e.vertices[0]), to_bundle_frame_position(e.vertices[1])],
            color_code: e.color_code,
            kind: e.kind,
            source: e.source,
        })
        .collect();

    Ok(PartGeometry {
        triangles: full_triangles,
        edges: full_edges,
        sources: vec![format!("ankerstein:{}", shape.id)],
        description: Some(format!("{:?} ({} — {})", shape.shape_type, shape.id, shape.source_citation)),
        license: None,
        author: None,
        uncertified: Vec::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_box_has_12_triangles() {
        let triangles = generate_box([25.0, 25.0, 25.0], 0);
        assert_eq!(triangles.len(), 12);
    }

    #[test]
    fn generate_box_bounds_match_the_given_dimensions() {
        let dims = [25.0, 12.5, 25.0];
        let triangles = generate_box(dims, 0);
        let mut min = [f64::INFINITY; 3];
        let mut max = [f64::NEG_INFINITY; 3];
        for tri in &triangles {
            for v in tri.vertices {
                for axis in 0..3 {
                    min[axis] = min[axis].min(v[axis]);
                    max[axis] = max[axis].max(v[axis]);
                }
            }
        }
        for axis in 0..3 {
            let span = max[axis] - min[axis];
            assert!((span - dims[axis]).abs() < 1e-9, "axis {axis}: span {span} != {}", dims[axis]);
        }
    }

    #[test]
    fn generate_shape_dispatches_blocks_prisms_and_rejects_arch_voussoirs() {
        let block = AnkersteinShape {
            id: "test-block".to_string(),
            shape_type: ShapeType::Block,
            dimensions_mm: [25.0, 25.0, 25.0],
            caliber: crate::catalog::Caliber::Gk,
            source_citation: "test fixture".to_string(),
        };
        assert!(generate_shape(&block, 4).is_ok());

        let prism = AnkersteinShape {
            shape_type: ShapeType::Prism,
            dimensions_mm: [50.0, 50.0, 50.0],
            ..block.clone()
        };
        assert!(generate_shape(&prism, 4).is_ok(), "the real 45\u{b0} isosceles case should now be implemented");

        let arch = AnkersteinShape {
            shape_type: ShapeType::ArchVoussoir,
            ..block
        };
        assert!(generate_shape(&arch, 4).is_err(), "M101's arch geometry isn't implemented yet");
    }

    #[test]
    fn generate_prism_has_8_triangles() {
        let triangles = generate_prism(50.0, 50.0, 0);
        assert_eq!(triangles.len(), 8);
    }

    #[test]
    fn generate_prism_bounds_match_a_real_bounding_box() {
        // Real citation (George Hardy, Richter's Anker Stone Building
        // Sets): the fifth historical set's prism shapes are sized so two
        // of them form a real cube - here, a 50x50x50mm one (GK's base
        // 25mm unit, doubled). The prism itself only fills half that
        // volume, but its bounding box should match exactly.
        let triangles = generate_prism(50.0, 50.0, 0);
        let mut min = [f64::INFINITY; 3];
        let mut max = [f64::NEG_INFINITY; 3];
        for tri in &triangles {
            for v in tri.vertices {
                for axis in 0..3 {
                    min[axis] = min[axis].min(v[axis]);
                    max[axis] = max[axis].max(v[axis]);
                }
            }
        }
        for axis in 0..3 {
            let span = max[axis] - min[axis];
            assert!((span - 50.0).abs() < 1e-9, "axis {axis}: bounding-box span {span} != 50.0");
        }
    }

    #[test]
    fn generate_prism_rejects_a_non_isosceles_case_via_generate_shape() {
        let lopsided = AnkersteinShape {
            id: "test-lopsided-prism".to_string(),
            shape_type: ShapeType::Prism,
            dimensions_mm: [50.0, 30.0, 50.0], // unequal X/Y legs — not the supported 45° case
            caliber: crate::catalog::Caliber::Gk,
            source_citation: "test fixture".to_string(),
        };
        assert!(generate_shape(&lopsided, 4).is_err());
    }

    /// Verifies every one of the prism's 8 faces has an outward-pointing
    /// normal — the same real correctness property `spex-ldraw::geometry`
    /// relies on LDraw's own BFC-CCW convention for, checked explicitly
    /// here since this geometry is hand-derived, not sourced from a
    /// pre-certified mesh file.
    #[test]
    fn prism_faces_point_outward() {
        use spex_ldraw::geometry::triangle_normal;
        let triangles = generate_prism(2.0, 3.0, 0);
        // Centroid of the whole solid's *bounding box* is the origin
        // (generate_prism centers on it) — for a right-triangular prism,
        // the true solid centroid is offset toward the right-angle
        // corner, so compare each face's own centroid-to-origin-ish
        // direction only loosely: the real, robust check is that a
        // triangle's normal has a positive dot product with the vector
        // from the prism's centroid to that triangle's own centroid — a
        // standard star-shaped-solid outward-normal test.
        let solid_centroid = [-2.0 / 6.0, -2.0 / 6.0, 0.0]; // mean of the 6 real cross-section*2 corners, roughly
        for tri in &triangles {
            let face_centroid = [
                (tri.vertices[0][0] + tri.vertices[1][0] + tri.vertices[2][0]) / 3.0,
                (tri.vertices[0][1] + tri.vertices[1][1] + tri.vertices[2][1]) / 3.0,
                (tri.vertices[0][2] + tri.vertices[1][2] + tri.vertices[2][2]) / 3.0,
            ];
            let outward_ish = [
                face_centroid[0] - solid_centroid[0],
                face_centroid[1] - solid_centroid[1],
                face_centroid[2] - solid_centroid[2],
            ];
            let n = triangle_normal(tri);
            let dot = n[0] * outward_ish[0] + n[1] * outward_ish[1] + n[2] * outward_ish[2];
            assert!(dot >= 0.0, "face {tri:?} has an inward-pointing normal {n:?} (dot {dot})");
        }
    }

    #[test]
    fn generate_box_edges_has_exactly_12_hard_edges() {
        let edges = generate_box_edges([25.0, 25.0, 25.0]);
        assert_eq!(edges.len(), 12);
        assert!(edges.iter().all(|e| !e.is_conditional()), "a box has no curved surface — every edge must be Hard");
    }

    #[test]
    fn generate_box_edges_endpoints_are_real_box_corners() {
        let dims = [25.0, 12.5, 50.0];
        let corners = box_corners(dims);
        let edges = generate_box_edges(dims);
        for e in &edges {
            for v in e.vertices {
                assert!(
                    corners.iter().any(|c| c.iter().zip(v.iter()).all(|(a, b)| (a - b).abs() < 1e-9)),
                    "edge endpoint {v:?} is not one of the real box corners {corners:?}"
                );
            }
        }
        // Every corner is used by at least one edge (no dangling/omitted corner).
        for c in corners {
            let touches = edges.iter().any(|e| e.vertices.iter().any(|v| v.iter().zip(c.iter()).all(|(a, b)| (a - b).abs() < 1e-9)));
            assert!(touches, "corner {c:?} is not touched by any edge");
        }
    }

    #[test]
    fn generate_box_edges_bounds_match_the_given_dimensions() {
        let dims = [25.0, 12.5, 25.0];
        let edges = generate_box_edges(dims);
        let mut min = [f64::INFINITY; 3];
        let mut max = [f64::NEG_INFINITY; 3];
        for e in &edges {
            for v in e.vertices {
                for axis in 0..3 {
                    min[axis] = min[axis].min(v[axis]);
                    max[axis] = max[axis].max(v[axis]);
                }
            }
        }
        for axis in 0..3 {
            let span = max[axis] - min[axis];
            assert!((span - dims[axis]).abs() < 1e-9, "axis {axis}: span {span} != {}", dims[axis]);
        }
    }

    #[test]
    fn generate_prism_edges_has_exactly_9_hard_edges() {
        let edges = generate_prism_edges(50.0, 50.0);
        assert_eq!(edges.len(), 9);
        assert!(edges.iter().all(|e| !e.is_conditional()));
    }

    #[test]
    fn generate_prism_edges_endpoints_are_real_prism_corners() {
        let corners = prism_corners(50.0, 30.0);
        let edges = generate_prism_edges(50.0, 30.0);
        for e in &edges {
            for v in e.vertices {
                assert!(
                    corners.iter().any(|c| c.iter().zip(v.iter()).all(|(a, b)| (a - b).abs() < 1e-9)),
                    "edge endpoint {v:?} is not one of the real prism corners {corners:?}"
                );
            }
        }
    }

    #[test]
    fn generate_shape_edges_dispatches_and_rejects_arch_voussoirs() {
        let block = AnkersteinShape {
            id: "test-block".to_string(),
            shape_type: ShapeType::Block,
            dimensions_mm: [25.0, 25.0, 25.0],
            caliber: crate::catalog::Caliber::Gk,
            source_citation: "test fixture".to_string(),
        };
        assert_eq!(generate_shape_edges(&block).unwrap().len(), 12);

        let prism = AnkersteinShape { shape_type: ShapeType::Prism, dimensions_mm: [50.0, 50.0, 50.0], ..block.clone() };
        assert_eq!(generate_shape_edges(&prism).unwrap().len(), 9);

        let arch = AnkersteinShape { shape_type: ShapeType::ArchVoussoir, ..block };
        assert!(generate_shape_edges(&arch).is_err());
    }

    #[test]
    fn to_bundle_frame_position_round_trips_through_the_mesh_bundle_conversion() {
        // The exact inverse claim `to_bundle_frame_position`'s doc comment
        // makes: feeding its output through `spex_mesh`'s own
        // `to_output_position`-shaped formula must reconstruct the original
        // real millimetre point unchanged. Duplicated here (rather than
        // depending on spex-mesh, which would be a real circular-ish
        // dependency for a geometry-generation crate) using the same public
        // `LDU_TO_MM` constant both sides share.
        let to_output_position = |p: [f64; 3]| [p[0] * LDU_TO_MM, -p[1] * LDU_TO_MM, p[2] * LDU_TO_MM];
        for real_mm in [[12.5, -6.25, 25.0], [0.0, 0.0, 0.0], [-100.0, 50.0, -3.2]] {
            let bundle_input = to_bundle_frame_position(real_mm);
            let round_tripped = to_output_position(bundle_input);
            for axis in 0..3 {
                assert!(
                    (round_tripped[axis] - real_mm[axis]).abs() < 1e-9,
                    "axis {axis}: {round_tripped:?} != original {real_mm:?}"
                );
            }
        }
    }

    #[test]
    fn to_part_geometry_produces_a_colourless_geometry_with_real_sources_and_edge_count() {
        let shape = AnkersteinShape {
            id: "gk-cube-full".to_string(),
            shape_type: ShapeType::Block,
            dimensions_mm: [25.0, 25.0, 25.0],
            caliber: crate::catalog::Caliber::Gk,
            source_citation: "test fixture".to_string(),
        };
        let geo = to_part_geometry(&shape).unwrap();
        assert_eq!(geo.triangles.len(), 12);
        assert_eq!(geo.edges.len(), 12);
        assert_eq!(geo.hard_edge_count(), 12);
        assert_eq!(geo.conditional_edge_count(), 0);
        assert!(geo.triangles.iter().all(|t| t.color_code.is_none()), "geometry must carry no baked colour");
        assert_eq!(geo.sources, vec!["ankerstein:gk-cube-full".to_string()]);
    }

    #[test]
    fn to_part_geometry_round_trips_through_the_real_mesh_bundle_conversion_to_the_original_corners() {
        // The strongest version of the frame-conversion claim: build a
        // `PartGeometry` via `to_part_geometry`, apply the exact same
        // position formula `spex_mesh::bundle::to_output_position` uses
        // (duplicated here for the same reason as the test above), and
        // confirm every resulting triangle vertex lands on a real box
        // corner — i.e. the whole `add_part` round trip is genuinely a
        // no-op for Ankerstein geometry, not just true for a single point.
        let dims = [25.0, 12.5, 50.0];
        let shape = AnkersteinShape {
            id: "test-block".to_string(),
            shape_type: ShapeType::Block,
            dimensions_mm: dims,
            caliber: crate::catalog::Caliber::Gk,
            source_citation: "test fixture".to_string(),
        };
        let geo = to_part_geometry(&shape).unwrap();
        let to_output_position = |p: [f64; 3]| [p[0] * LDU_TO_MM, -p[1] * LDU_TO_MM, p[2] * LDU_TO_MM];
        let real_corners = box_corners(dims);
        for tri in &geo.triangles {
            for v in tri.vertices {
                let out = to_output_position(v);
                assert!(
                    real_corners.iter().any(|c| c.iter().zip(out.iter()).all(|(a, b)| (a - b).abs() < 1e-9)),
                    "converted vertex {out:?} is not a real box corner {real_corners:?}"
                );
            }
        }
    }
}
