"""Emits `recipes/tokens.json` — A2-S03's counting row, and the overrun.

    python3 scripts/ldraw/gen-tokens-recipe.py     # run from the repo's spex/

The screenplay asks for two populations in one shot: "tokens spill out and
arrange themselves into a counting row, one per beat. THEN THE COUNT OVERRUNS:
tokens keep spilling past what the row can hold and past what the eye can
track." The recipe had the first forty and stopped, and the documentation frame
at 1:43 shows exactly what that costs — a tidy bead chain of forty, which is
the one thing a viewer CAN count. Tallying by object ceasing to scale is the
actual historical reason a bulla was sealed, and it has to be an image.

So: TWO RECIPES AND TWO SCENES, not one longer list. That is not tidiness — it
is the only way to get the two phases the screenplay asks for. A dissolve is
ONE amount written to every instance of a scene (`DissolveController.set`), and
the erosion noise is sampled in world position, so a single scene of 240 arrives
as one spreading stain and never as "the row, and then the overrun". Two scenes
give the shot two dissolve tracks and therefore two moments, which is what the
sentence describes.

The scatter is deterministic (splitmix64, the same generator the runtime
assembly and the token flow use) and SNAPPED TO WHOLE STUDS, because this piece
builds nothing it could not build: a counter lying between studs is a render,
not a model.
"""
import json

ROW_START, ROW_STEP, ROW_N = 500, 3, 40
SPILL_N = 200
SPILL_X = (ROW_START - 2, ROW_START + ROW_STEP * ROW_N + 40)  # past the row's end
SPILL_Z = (-20, 20)
SEED = 0x9E3779B97F4A7C15


def splitmix64(x):
    x = (x + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
    return z ^ (z >> 31)


def step(x, z):
    return {
        "primitive": "Wall",
        "at": {"xStuds": x, "zStuds": z, "yPlates": 0, "orientationDeg": 0},
        "params": {"widthStuds": 1, "heightPlates": 3, "depthStuds": 1,
                   "bond": "Stack", "color": "lehm"},
    }


ROW_STEPS = [step(ROW_START + i * ROW_STEP, 0) for i in range(ROW_N)]
SPILL_STEPS = []

taken = {(s["at"]["xStuds"], s["at"]["zStuds"]) for s in ROW_STEPS}
i = 0
while len(SPILL_STEPS) < SPILL_N:
    a = splitmix64(SEED + i * 2)
    b = splitmix64(SEED + i * 2 + 1)
    i += 1
    x = SPILL_X[0] + a % (SPILL_X[1] - SPILL_X[0])
    z = SPILL_Z[0] + b % (SPILL_Z[1] - SPILL_Z[0])
    if (x, z) in taken:
        continue
    taken.add((x, z))
    SPILL_STEPS.append(step(x, z))

doc = {
    "version": 1,
    "id": "tokens",
    "title": "The tokens, spilled and then overrunning the row (A2-S03)",
    "scale": {"studsPerMetre": 25,
              "note": "The bulla's own scale -- these came out of it."},
    "palette": {"lehm": 84},
    "_substitution": (
        "The screenplay asks for 1x1 ROUND plates. PartSet::Classic has no round part "
        "with a measured footprint, so these are 1x1 bricks (3005.dat). Stated rather "
        "than silently swapped."
    ),
    "_note": [
        "THE COUNTING ROW. The overrun is `tokens-ueberlauf.json`, a scene of its own,",
        "because a dissolve writes ONE amount to every instance of a scene and the",
        "erosion noise is sampled in world position -- one scene of 240 would arrive as",
        "a single spreading stain, and the screenplay asks for the row first and the",
        "overrun after it. Two scenes, two dissolve tracks, two moments.",
        "",
        f"{ROW_N} counters: x from {ROW_START} in threes, z = 0. Byte-for-byte the",
        "placements this recipe had before the overrun existed, so the first half of",
        "A2-S03 is unchanged.",
    ],
    "steps": ROW_STEPS,
}

SPILL_DOC = {
    "version": 1,
    "id": "tokens-ueberlauf",
    "title": "The overrun -- the count past what the row can hold (A2-S03)",
    "scale": {"studsPerMetre": 25, "note": "The row's own scale."},
    "palette": {"lehm": 84},
    "_note": [
        f"{SPILL_N} more counters, scattered around and past the counting row of",
        "`tokens.json`. The screenplay: tokens keep spilling",
        "'past what the row can hold and past what the eye can track'. Forty in a line",
        "is the one number a viewer can count, and counting is the thing this shot is",
        "about ceasing to work. Two hundred and forty cannot be counted, which is the",
        "image and also the history: tallying by object stops scaling, and that is why",
        "the bulla was sealed.",
        "",
        "The scatter is splitmix64 from a fixed seed and snapped to whole studs -- a",
        "counter lying between studs is a render and not a model. Generated by",
        "scripts/ldraw/gen-tokens-recipe.py; edit that, not this.",
        "",
        "It is spread over a BAND rather than a longer line for two reasons: the row's",
        "line already runs out of frame, so more of it would add nothing an eye can",
        "see; and past x = 660 studs is where A2-S04's coin stands.",
    ],
    "steps": SPILL_STEPS,
}
open("recipes/tokens.json", "w").write(json.dumps(doc, indent=1) + "\n")
open("recipes/tokens-ueberlauf.json", "w").write(json.dumps(SPILL_DOC, indent=1) + "\n")
print(f"wrote recipes/tokens.json ({ROW_N}) and recipes/tokens-ueberlauf.json ({SPILL_N})")
