"""NOT YET WIRED INTO THE SHOW. Emits `recipes/stonehenge.json` — the sarsen circle and the trilithon horseshoe.

    python3 scripts/ldraw/gen-stonehenge.py     # from the repo's spex/

WHY THIS REPLACED A HAND-AUTHORED .ldr
--------------------------------------
`ldraw-scenes/stonehenge.ldr` got every HEIGHT from the literature and then
built each stone out of a single column of 1x2 or 1x4 bricks, stating plainly
in its own header that it "does not attempt to match real stone WIDTH/DEPTH"
because doing so "would need roughly 10-14 studs per course per stone and push
the part count into the tens of thousands".

On screen that reads exactly as what it is: thin T-shapes, with lintels that
look far too long because the uprights they sit on are a tenth of their real
width. The proportions the eye actually judges a megalith by are width against
height, and those were the two the file traded away.

So the stones are built by the recipe engine's `Wall` instead of by hand, and
the widths are the cited ones. The part count is the price and it is paid: a
`Wall` of 10 x 5 studs is bricks the engine lays, not lines anybody types.

THE NUMBERS, all from the same sources the .ldr cited (Cleal, Walker &
Montague 1995 via English Heritage, cross-checked against Wikipedia's "Sarsen
structures"), and all at ONE scale factor:

  Sarsen circle     30 uprights on a 30 m circle
  Circle upright    2.13 m wide x 1.06 m deep x 4.11 m tall
  Circle lintel     3.2 m long x 1.0 m wide x 0.8 m thick, top 4.9 m up
  Trilithons        5, graded: 6.0 m, 6.65 m (interpolated), 7.3 m
  Trilithon lintel  2 x upright width + the ~1 m sarsen spacing = 5.26 m

SCALE: 20 studs per metre, the same as `rom.json` and `uruk-wall.json`, so the
three stone scenes of the piece share one. A stud is 8 mm, so the circle is
600 studs across and the Great Trilithon 146 studs tall.
"""
import json, math

SPM = 5                      # studs per metre — see the note: a megalith at rom.json's 20 is tens of thousands of bricks per stone
def st(m): return max(1, round(m * SPM))
def pl(m): return max(1, round(m * SPM * 20 / 8))   # 1 plate = 8 LDU, 1 stud = 20

CIRCLE_R_M = 15.0
N_UPRIGHTS = 30
UP_W, UP_D, UP_H = 2.13, 1.06, 4.11
LINTEL_L, LINTEL_W, LINTEL_T = 3.2, 1.0, 0.8
LINTEL_TOP = 4.9

TRILITHON_H = [6.0, 6.65, 7.3, 6.65, 6.0]
TRI_LINTEL_L = 2 * UP_W + 1.0
TRI_R_M = 7.0

steps = []
def wall(x, z, y_plates, w, d, h, deg, color):
    steps.append({
        "primitive": "Wall",
        "at": {"xStuds": int(round(x)), "zStuds": int(round(z)),
               "yPlates": int(y_plates), "orientationDeg": int(round(deg)) % 360},
        "params": {"widthStuds": int(w), "heightPlates": int(h), "depthStuds": int(d),
                   "bond": "Running", "color": color},
    })

CX = 400   # stage centre, in studs

# --- the sarsen circle: uprights, then the lintel ring on top of them.
for i in range(N_UPRIGHTS):
    a = 2 * math.pi * i / N_UPRIGHTS
    x = CX + CIRCLE_R_M * math.cos(a) * SPM
    z = CIRCLE_R_M * math.sin(a) * SPM
    deg = math.degrees(a) + 90        # tangential: the stone faces out of the ring
    wall(x, z, 0, st(UP_W), st(UP_D), pl(UP_H), deg, "sarsen")

# One lintel per gap, sitting where the real ring sits: its underside at the
# uprights' top, its own centre on the circle between two of them.
lintel_y = pl(LINTEL_TOP - LINTEL_T)
for i in range(N_UPRIGHTS):
    a = 2 * math.pi * (i + 0.5) / N_UPRIGHTS
    x = CX + CIRCLE_R_M * math.cos(a) * SPM
    z = CIRCLE_R_M * math.sin(a) * SPM
    deg = math.degrees(a) + 90
    wall(x, z, -lintel_y, st(LINTEL_L), st(LINTEL_W), pl(LINTEL_T), deg, "sarsen")

# --- the trilithon horseshoe: five, opening to the north-east like the real one.
for i, h in enumerate(TRILITHON_H):
    a = math.radians(-120 + i * 60)
    cx = CX + TRI_R_M * math.cos(a) * SPM
    cz = TRI_R_M * math.sin(a) * SPM
    deg = math.degrees(a) + 90
    # the pair of uprights, offset either side of the trilithon's own axis
    half = (UP_W + 0.5) * SPM / 2
    ox, oz = -math.sin(a) * half, math.cos(a) * half
    for s in (1, -1):
        wall(cx + s * ox, cz + s * oz, 0, st(UP_W), st(UP_D), pl(h), deg, "sarsen")
    wall(cx, cz, -pl(h), st(TRI_LINTEL_L), st(LINTEL_W), pl(LINTEL_T), deg, "sarsen")

doc = {
    "version": 1,
    "id": "stonehenge",
    "title": "Stonehenge, c. 2500 BCE — sarsen circle and trilithon horseshoe (A1-S06)",
    "scale": {"studsPerMetre": SPM,
              "note": "The same scale as rom.json and uruk-wall.json, so the piece's three stone scenes share one."},
    "palette": {"sarsen": 71},
    "_note": [
        "GENERATED by scripts/ldraw/gen-stonehenge.py; edit that, not this.",
        "",
        "REPLACES ldraw-scenes/stonehenge.ldr, which had every HEIGHT from the",
        "literature and no WIDTH at all: each stone was one column of 1x2 or 1x4",
        "bricks, and its own header said so -- matching the real cross-section",
        "'would need roughly 10-14 studs per course per stone'. On screen that is",
        "thin T-shapes under lintels that look far too long, because the uprights",
        "under them are a tenth of their real width. Width against height is the",
        "proportion an eye judges a megalith by, and it was the one traded away.",
        "",
        f"Circle upright {UP_W} x {UP_D} x {UP_H} m -> {st(UP_W)} x {st(UP_D)} studs, {pl(UP_H)} plates.",
        f"Circle lintel {LINTEL_L} x {LINTEL_W} x {LINTEL_T} m, top at {LINTEL_TOP} m.",
        f"Trilithons {TRILITHON_H} m; the 6.65 is the arithmetic midpoint of the",
        "documented 6.0 and 7.3, flagged as an interpolation in the .ldr it came",
        "from and still an interpolation here.",
        f"Trilithon lintel {TRI_LINTEL_L} m = twice the upright width plus the cited",
        "~1 m sarsen spacing, since no trilithon-specific figure is published.",
        "",
        "Colour 71 Light_Bluish_Grey -- Steingrau, as before.",
    ],
    "steps": steps,
}
open("recipes/stonehenge.json", "w").write(json.dumps(doc, indent=1) + "\n")
print(f"wrote recipes/stonehenge.json — {len(steps)} stones")
