//! The real LDraw grid, the real 24 axis-aligned orientations, real part
//! footprints, and `validate()` — the part of M72 that decides whether an
//! emitted placement is grid-legal, not just parseable.
//!
//! **The grid, real numbers** (also stated in `../../BRICKs.md` and
//! `docs/fugen/phase4-kit.md`): 1 LDU = 0.4 mm. Stud pitch is 8.0 mm = 20
//! LDU. Plate height is 3.2 mm = 8 LDU. Brick height is 9.6 mm = 24 LDU (=
//! 3 plates). A grid-legal translation is an integer multiple of 10 LDU
//! (half a stud, to permit real jumper-plate offsets) in X/Z and an integer
//! multiple of 8 LDU (one plate) in Y.

use std::collections::HashMap;
use std::sync::OnceLock;

pub const STUD_LDU: f64 = 20.0;
pub const HALF_STUD_LDU: f64 = 10.0;
pub const PLATE_LDU: f64 = 8.0;
pub const BRICK_LDU: f64 = 24.0;
/// A standard brick is 3 plates tall — the coursing unit every primitive in
/// `primitives.rs` builds on.
pub const BRICK_PLATES: u32 = 3;

/// Tolerance for float comparisons against the grid, in LDU. Generous
/// enough to absorb f64 accumulation error over a few dozen placements,
/// tight enough that a real half-stud (10 LDU) or full-stud (20 LDU) error
/// never passes.
const EPSILON_LDU: f64 = 1e-6;

/// A grid-legal position: X/Z in half-studs (so a whole number of 10 LDU
/// steps), Y in plates (whole 8 LDU steps).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
pub struct GridPos {
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

impl GridPos {
    pub fn new(x: i32, y: i32, z: i32) -> Self {
        GridPos { x, y, z }
    }

    pub fn to_ldu(self) -> [f64; 3] {
        [
            self.x as f64 * HALF_STUD_LDU,
            self.y as f64 * PLATE_LDU,
            self.z as f64 * HALF_STUD_LDU,
        ]
    }

    pub fn translated(self, dx_half_studs: i32, dy_plates: i32, dz_half_studs: i32) -> Self {
        GridPos {
            x: self.x + dx_half_studs,
            y: self.y + dy_plates,
            z: self.z + dz_half_studs,
        }
    }
}

/// One of the real 24 axis-aligned orientations — the chiral (proper,
/// determinant +1) rotational symmetry group of the cube. An index into a
/// table generated by composing 90-degree rotations about the three axes
/// and deduplicating, never a hand-enumerated matrix: 24 hand-typed 3x3
/// matrices is exactly the kind of thing that is wrong in one entry and
/// looks fine.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Orientation(pub u8);

impl Orientation {
    pub const IDENTITY: Orientation = Orientation(0);

    /// The real LDraw row-major 3x3 rotation matrix for this orientation
    /// (`a b c / d e f / g h i`, as `1 <color> x y z a b c d e f g h i
    /// <part>` line's own 9 numbers).
    pub fn matrix(self) -> [f64; 9] {
        let table = orientation_table();
        table[self.0 as usize]
    }

    /// All 24, in the table's own stable order (index 0 is always
    /// `IDENTITY`).
    pub fn all() -> impl Iterator<Item = Orientation> {
        (0..orientation_table().len() as u8).map(Orientation)
    }

    /// The orientation among the 24 whose yaw (rotation about Y, LDraw's
    /// up/down axis) is closest to `yaw_deg`, for primitives arranged
    /// around an arc or circle (`recipe.rs`'s `arrangeOn`) where the exact
    /// tangent angle is real-valued but the emitted placement still has to
    /// land on one of the 24 legal rotations. Snapping is a documented
    /// approximation, not silent: a recipe that needs true continuous
    /// rotation is off-grid by construction and should say so.
    pub fn nearest_yaw(yaw_deg: f64) -> Orientation {
        // The four pure-yaw members of the 24: identity and the three
        // 90/180/270-degree rotations about Y. Found by filtering the real
        // table rather than hand-picking indices.
        let table = orientation_table();
        let target = yaw_deg.rem_euclid(360.0);
        let mut best = Orientation::IDENTITY;
        let mut best_err = f64::MAX;
        for (i, m) in table.iter().enumerate() {
            // A pure-yaw rotation leaves Y fixed: row/col 1 (0-indexed) is
            // (0,1,0) and (0,1,0).
            if (m[4] - 1.0).abs() > 1e-9 {
                continue;
            }
            // atan2(sin, cos) from the matrix's own X-row: a=cos, c=sin for
            // LDraw's row-major convention with rotation about +Y.
            let angle = m[2].atan2(m[0]).to_degrees().rem_euclid(360.0);
            let err = angle_diff(angle, target);
            if err < best_err {
                best_err = err;
                best = Orientation(i as u8);
            }
        }
        best
    }
}

fn angle_diff(a: f64, b: f64) -> f64 {
    let d = (a - b).rem_euclid(360.0);
    d.min(360.0 - d)
}

pub(crate) fn mat_mul(a: [f64; 9], b: [f64; 9]) -> [f64; 9] {
    // Row-major 3x3 multiply, a*b.
    let mut out = [0.0; 9];
    for r in 0..3 {
        for c in 0..3 {
            let mut sum = 0.0;
            for k in 0..3 {
                sum += a[r * 3 + k] * b[k * 3 + c];
            }
            out[r * 3 + c] = sum;
        }
    }
    out
}

pub(crate) fn mat_vec(m: [f64; 9], v: [f64; 3]) -> [f64; 3] {
    [
        m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
        m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
        m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
    ]
}

fn key(m: [f64; 9]) -> [i64; 9] {
    let mut k = [0i64; 9];
    for i in 0..9 {
        k[i] = m[i].round() as i64;
    }
    k
}

/// Generates the real 24-element rotation group by BFS closure of two
/// 90-degree generators (rotation about X and about Y — any two of the
/// three real axis generators already generate the full chiral octahedral
/// group), then sorts for a stable, deterministic order and swaps identity
/// into index 0 so `Orientation::IDENTITY` is always `Orientation(0)`.
fn generate_orientations() -> Vec<[f64; 9]> {
    const IDENTITY: [f64; 9] = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0];
    // 90-degree rotation about X (LDraw row-major: rotates Y toward Z).
    const ROT_X: [f64; 9] = [1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0];
    // 90-degree rotation about Y (rotates Z toward X).
    const ROT_Y: [f64; 9] = [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, -1.0, 0.0, 0.0];

    let mut seen: HashMap<[i64; 9], [f64; 9]> = HashMap::new();
    seen.insert(key(IDENTITY), IDENTITY);
    let mut frontier = vec![IDENTITY];
    while !frontier.is_empty() {
        let mut next = Vec::new();
        for m in &frontier {
            for g in [ROT_X, ROT_Y] {
                let candidate = mat_mul(g, *m);
                let k = key(candidate);
                if !seen.contains_key(&k) {
                    seen.insert(k, candidate);
                    next.push(candidate);
                }
            }
        }
        frontier = next;
    }

    let mut all: Vec<[f64; 9]> = seen.into_values().collect();
    all.sort_by(|a, b| key(*a).cmp(&key(*b)));
    // Guarantee identity is index 0 regardless of where lexicographic sort
    // put it, so `Orientation::IDENTITY` stays `Orientation(0)` by
    // construction.
    if let Some(pos) = all.iter().position(|m| key(*m) == key(IDENTITY)) {
        all.swap(0, pos);
    }
    all
}

fn orientation_table() -> &'static Vec<[f64; 9]> {
    static TABLE: OnceLock<Vec<[f64; 9]>> = OnceLock::new();
    TABLE.get_or_init(generate_orientations)
}

/// A part's real footprint: width/depth in whole studs, height in whole
/// plates — what `validate()` needs to check overlap and support, and what
/// `Wall`/`Column`/etc need to know how far to advance between placements.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Footprint {
    pub studs_w: u32,
    pub studs_d: u32,
    pub height_plates: u32,
}

/// Real part footprints for the kit's working part set.
///
/// **Source.** Not typed from memory: measured from the real LDraw geometry
/// this repository already fetches and caches (`spex_ldraw::resolve_part_full`),
/// by taking each part's triangle bounding box and converting through the
/// real LDU constants above. The stud-plane extent (X/Z) matches the
/// bounding box directly; the *height* is **not** the raw Y extent, because
/// a brick's stud protrudes above its own Y=0 reference plane without
/// adding to the real stacking pitch — the number that matters is the
/// depth of the underside tube (max Y in LDraw's down-positive frame),
/// which is exactly the real brick/plate height. Measured 2026-08 against
/// the real cached `parts/3005.dat`, `3004.dat`, `3010.dat`, `3710.dat`,
/// `2431.dat`, `3009.dat`, `3022.dat`, `3020.dat` (see
/// `crates/spex-build/tests/footprint_provenance.rs`, `#[ignore]`d because
/// it needs the real LDraw cache, same convention as `spex-ldraw`'s own
/// network-dependent tests):
///
/// | part | studs (W x D) | stacking height | measured max-Y (LDU) |
/// |---|---|---|---|
/// | `3005.dat` Brick 1 x 1  | 1 x 1 | 3 plates (1 brick) | 24.0 |
/// | `3004.dat` Brick 1 x 2  | 2 x 1 | 3 plates (1 brick) | 24.0 |
/// | `3010.dat` Brick 1 x 4  | 4 x 1 | 3 plates (1 brick) | 24.0 |
/// | `3009.dat` Brick 1 x 6  | 6 x 1 | 3 plates (1 brick) | 24.0 |
/// | `3710.dat` Plate 1 x 4  | 4 x 1 | 1 plate            | 8.0  |
/// | `2431.dat` Tile 1 x 4   | 4 x 1 | 1 plate            | 8.0  |
/// | `3022.dat` Plate 2 x 2  | 2 x 2 | 1 plate            | 8.0  |
/// | `3020.dat` Plate 2 x 4  | 4 x 2 | 1 plate            | 8.0  |
///
/// These also match this repo's own established real numbers
/// (`BRICKs.md`'s "brick height 9.6mm = 24 LDU = 3 plates").
///
/// `3022.dat`/`3020.dat` are measured and cited here so `validate()` can
/// check real placements of them, but **no primitive in this crate emits
/// them yet** — every current primitive (`Wall`/`Column`/`Ziggurat`/...)
/// tiles one row/course at a time assuming every real part is exactly
/// 1-stud-deep, which a 2-studs-deep plate does not fit; generalizing that
/// to real 2D footprint consumption is a genuine, separate primitive/tiler
/// change, not a footprint-table addition. `3009.dat` has no such
/// restriction (still 1-stud-deep) and *is* wired into `PartSet::Classic`'s
/// greedy tiler below.
#[derive(Clone, Debug, Default)]
pub struct FootprintTable(HashMap<String, Footprint>);

impl FootprintTable {
    pub fn new() -> Self {
        FootprintTable(HashMap::new())
    }

    pub fn insert(&mut self, part: impl Into<String>, footprint: Footprint) {
        self.0.insert(part.into(), footprint);
    }

    pub fn get(&self, part: &str) -> Option<Footprint> {
        self.0.get(part).copied()
    }

    /// The real, cited table for the kit's current working part set (see
    /// the type doc comment above for the measurement).
    pub fn standard() -> Self {
        let mut t = FootprintTable::new();
        t.insert("3005.dat", Footprint { studs_w: 1, studs_d: 1, height_plates: BRICK_PLATES });
        t.insert("3004.dat", Footprint { studs_w: 2, studs_d: 1, height_plates: BRICK_PLATES });
        t.insert("3010.dat", Footprint { studs_w: 4, studs_d: 1, height_plates: BRICK_PLATES });
        t.insert("3710.dat", Footprint { studs_w: 4, studs_d: 1, height_plates: 1 });
        t.insert("2431.dat", Footprint { studs_w: 4, studs_d: 1, height_plates: 1 });
        t.insert("3009.dat", Footprint { studs_w: 6, studs_d: 1, height_plates: BRICK_PLATES });
        t.insert("3022.dat", Footprint { studs_w: 2, studs_d: 2, height_plates: 1 });
        t.insert("3020.dat", Footprint { studs_w: 4, studs_d: 2, height_plates: 1 });
        t
    }
}

/// A real placement: which real part, what real color, and where. Kept
/// separate from `spex_ldraw::scene::Placement` deliberately — that type is
/// the *parsed* form of an existing `.ldr`'s type-1 lines; this one is the
/// *authored* form a primitive emits, before it is serialised, and carries
/// the extra bit (`declared_off_grid`) `validate()` needs.
#[derive(Clone, Debug)]
pub struct Placement {
    pub part: String,
    pub color: u32,
    pub translation_ldu: [f64; 3],
    pub matrix: [f64; 9],
    /// Set by the *emitting primitive* when a placement is an intentional
    /// off-grid connection (e.g. a future angled voussoir) — `validate()`
    /// still records it, but as a declared exception the recipe's
    /// `"knownIllegal"` array can list (acceptance criterion 2), not as an
    /// undeclared `Illegality`.
    pub declared_off_grid: bool,
    /// Which real construction stage this placement belongs to, 0-based.
    /// A primitive sets this to stage its own internal structure (e.g.
    /// `Ziggurat` numbers by tier); `recipe::build_recipe` then offsets
    /// each emitted instance's own numbering so stages stay distinct
    /// across a whole recipe. `recipe::write_ldr` turns runs of equal
    /// `build_step` into real `0 STEP` lines, which is what lets the
    /// already-shipped `spex-mesh`/viewer choreography (`instanceBuildSteps`,
    /// `AssemblyChoreography`) animate a real progressive assembly —
    /// see `docs/fugen/phase2-show.md`'s M64 section. Left at the default
    /// `0` for every placement means "no animation data," not an error.
    pub build_step: u32,
}

impl Placement {
    /// The common case: a real part at a real grid-legal position and one
    /// of the real 24 orientations.
    pub fn on_grid(pos: GridPos, orientation: Orientation, part: impl Into<String>, color: u32) -> Self {
        Placement {
            part: part.into(),
            color,
            translation_ldu: pos.to_ldu(),
            matrix: orientation.matrix(),
            declared_off_grid: false,
            build_step: 0,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Illegality {
    OffGridTranslation { placement_index: usize, axis: char, ldu: f64 },
    NonAxisRotation { placement_index: usize },
    Overlap { a: usize, b: usize, overlap_ldu3: f64 },
    /// No supporting part directly below and not resting on the ground
    /// (`y == 0`, this kit's documented convention for "the base course").
    Floating { placement_index: usize },
}

/// World-space AABB of one placement, from its footprint. Only meaningful
/// for a placement whose rotation is (or is close to) one of the real 24 —
/// callers skip placements with no footprint entry or a genuinely free
/// rotation.
fn world_aabb(p: &Placement, fp: Footprint) -> ([f64; 3], [f64; 3]) {
    let half = [fp.studs_w as f64 * STUD_LDU / 2.0, 0.0, fp.studs_d as f64 * STUD_LDU / 2.0];
    let height = fp.height_plates as f64 * PLATE_LDU;
    // 8 local corners of the part's own box, local Y from 0 (top ref) to
    // height (bottom of tube, LDraw down-positive).
    let mut min = [f64::MAX; 3];
    let mut max = [f64::MIN; 3];
    for &sx in &[-1.0, 1.0] {
        for &sz in &[-1.0, 1.0] {
            for &sy in &[0.0, 1.0] {
                let local = [sx * half[0], sy * height, sz * half[2]];
                let world = [
                    p.matrix[0] * local[0] + p.matrix[1] * local[1] + p.matrix[2] * local[2] + p.translation_ldu[0],
                    p.matrix[3] * local[0] + p.matrix[4] * local[1] + p.matrix[5] * local[2] + p.translation_ldu[1],
                    p.matrix[6] * local[0] + p.matrix[7] * local[1] + p.matrix[8] * local[2] + p.translation_ldu[2],
                ];
                for i in 0..3 {
                    min[i] = min[i].min(world[i]);
                    max[i] = max[i].max(world[i]);
                }
            }
        }
    }
    (min, max)
}

fn aabb_overlap_volume(a: ([f64; 3], [f64; 3]), b: ([f64; 3], [f64; 3])) -> f64 {
    let mut vol = 1.0;
    for i in 0..3 {
        let lo = a.0[i].max(b.0[i]);
        let hi = a.1[i].min(b.1[i]);
        let overlap = (hi - lo).max(0.0);
        vol *= overlap;
    }
    vol
}

fn is_axis_orientation(m: [f64; 9]) -> bool {
    orientation_table().iter().any(|t| t.iter().zip(m.iter()).all(|(a, b)| (a - b).abs() < 1e-6))
}

/// Validates a whole emitted scene. Returns every real problem found, not
/// just the first — a build report, not an assertion (acceptance criterion
/// 2: the CLI prints every one of these).
pub fn validate(placements: &[Placement], footprints: &FootprintTable) -> Vec<Illegality> {
    let mut problems = Vec::new();

    for (i, p) in placements.iter().enumerate() {
        if p.declared_off_grid {
            continue;
        }
        for (axis_idx, axis) in [(0, 'x'), (2, 'z')] {
            let v = p.translation_ldu[axis_idx];
            let rem = (v / HALF_STUD_LDU).round() * HALF_STUD_LDU - v;
            if rem.abs() > EPSILON_LDU {
                problems.push(Illegality::OffGridTranslation { placement_index: i, axis, ldu: v });
            }
        }
        {
            let v = p.translation_ldu[1];
            let rem = (v / PLATE_LDU).round() * PLATE_LDU - v;
            if rem.abs() > EPSILON_LDU {
                problems.push(Illegality::OffGridTranslation { placement_index: i, axis: 'y', ldu: v });
            }
        }
        if !is_axis_orientation(p.matrix) {
            problems.push(Illegality::NonAxisRotation { placement_index: i });
        }
    }

    // Overlap + support, only for placements whose part has a known real
    // footprint — the kit only knows how to reason about parts it has real
    // dimensions for.
    let boxes: Vec<Option<([f64; 3], [f64; 3])>> = placements
        .iter()
        .map(|p| footprints.get(&p.part).map(|fp| world_aabb(p, fp)))
        .collect();

    for i in 0..placements.len() {
        let Some(bi) = boxes[i] else { continue };
        for j in (i + 1)..placements.len() {
            let Some(bj) = boxes[j] else { continue };
            let vol = aabb_overlap_volume(bi, bj);
            if vol > 1.0 {
                // >1 LDU^3 (~0.4mm^3 side) so two parts merely touching at
                // a shared face (zero-volume overlap up to float error)
                // never counts.
                problems.push(Illegality::Overlap { a: i, b: j, overlap_ldu3: vol });
            }
        }
    }

    // LDraw's Y axis points DOWN (see `ldraw-scenes/monolith.ldr`'s own
    // comment: "translation_y = -(height_from_base + own_height)"), so a
    // placement's physical *bottom* is its world AABB's **max** Y and its
    // physical *top* is the **min** Y. This kit's ground plane is world
    // Y=0: the lowest placement's physical bottom sits exactly there, the
    // same convention `monolith.ldr` already established (its lowest
    // brick's tube-bottom is at y=0, its own translation is y=-24).
    //
    // Support propagates two ways, both real: **vertically**, one part's
    // bottom resting on another's top (ordinary stacking), and
    // **horizontally**, two parts in the *same course* whose faces meet —
    // a real stud-to-tube clutch connection exists there too (`BRICKs.md`'s
    // "clutch power"), which is exactly why a real lintel or arch spanning
    // a gap between two piers does not collapse even though its middle
    // brick has nothing directly below it. Computed as a fixed point:
    // start from what's grounded, propagate through both kinds of contact
    // until nothing new is reached, and whatever is left unreached is a
    // real `Floating` problem.
    let n = placements.len();
    let mut supported = vec![false; n];
    for (i, b) in boxes.iter().enumerate() {
        if let Some((_, max_i)) = b {
            if max_i[1].abs() < EPSILON_LDU {
                supported[i] = true;
            }
        }
    }
    let mut changed = true;
    while changed {
        changed = false;
        for i in 0..n {
            if supported[i] {
                continue;
            }
            let Some((min_i, max_i)) = boxes[i] else { continue };
            for (j, b) in boxes.iter().enumerate() {
                if i == j || !supported[j] {
                    continue;
                }
                let Some((min_j, max_j)) = *b else { continue };
                let xz_overlap = overlap_1d(min_i[0], max_i[0], min_j[0], max_j[0]) > EPSILON_LDU
                    && overlap_1d(min_i[2], max_i[2], min_j[2], max_j[2]) > EPSILON_LDU;
                let vertical = xz_overlap && (min_j[1] - max_i[1]).abs() < EPSILON_LDU;

                let same_height = (min_i[1] - min_j[1]).abs() < EPSILON_LDU && (max_i[1] - max_j[1]).abs() < EPSILON_LDU;
                let x_touch = touch_1d(min_i[0], max_i[0], min_j[0], max_j[0]);
                let z_touch = touch_1d(min_i[2], max_i[2], min_j[2], max_j[2]);
                let x_overlap = overlap_1d(min_i[0], max_i[0], min_j[0], max_j[0]) > EPSILON_LDU;
                let z_overlap = overlap_1d(min_i[2], max_i[2], min_j[2], max_j[2]) > EPSILON_LDU;
                let horizontal_clutch = same_height && ((x_touch && z_overlap) || (z_touch && x_overlap));

                if vertical || horizontal_clutch {
                    supported[i] = true;
                    changed = true;
                    break;
                }
            }
        }
    }
    for (i, &ok) in supported.iter().enumerate() {
        if !ok && boxes[i].is_some() {
            problems.push(Illegality::Floating { placement_index: i });
        }
    }

    problems
}

fn overlap_1d(a0: f64, a1: f64, b0: f64, b1: f64) -> f64 {
    (a1.min(b1) - a0.max(b0)).max(0.0)
}

fn touch_1d(a0: f64, a1: f64, b0: f64, b1: f64) -> bool {
    (a1 - b0).abs() < EPSILON_LDU || (b1 - a0).abs() < EPSILON_LDU
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_exactly_24_distinct_orthonormal_matrices() {
        let table = orientation_table();
        assert_eq!(table.len(), 24, "the real chiral octahedral group has exactly 24 elements");
        for m in table.iter() {
            // Every real axis-aligned rotation matrix has exactly one
            // nonzero entry (+-1) per row and column, determinant +1.
            let det = m[0] * (m[4] * m[8] - m[5] * m[7]) - m[1] * (m[3] * m[8] - m[5] * m[6]) + m[2] * (m[3] * m[7] - m[4] * m[6]);
            assert!((det - 1.0).abs() < 1e-9, "matrix {m:?} must be a proper rotation (det=1), got {det}");
        }
    }

    #[test]
    fn identity_is_always_index_zero() {
        assert_eq!(Orientation::IDENTITY.0, 0);
        assert_eq!(Orientation::IDENTITY.matrix(), [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]);
    }

    #[test]
    fn grid_pos_converts_to_real_ldu() {
        let pos = GridPos::new(2, 3, -1);
        assert_eq!(pos.to_ldu(), [20.0, 24.0, -10.0]);
    }

    #[test]
    fn validate_flags_an_off_grid_translation_on_the_failing_axis_only() {
        let placements = vec![Placement {
            part: "3005.dat".into(),
            color: 15,
            // y=-24 rests exactly on the ground (bottom at y=0), isolating
            // this case to x's real off-grid violation only.
            translation_ldu: [5.0, -24.0, 0.0], // 5 LDU is not a multiple of 10
            matrix: Orientation::IDENTITY.matrix(),
            declared_off_grid: false,
            build_step: 0,
        }];
        let problems = validate(&placements, &FootprintTable::standard());
        assert_eq!(problems.len(), 1, "{problems:?}");
        assert!(matches!(problems[0], Illegality::OffGridTranslation { axis: 'x', .. }));
    }

    #[test]
    fn validate_reports_multiple_real_problems_not_just_the_first() {
        let placements = vec![
            Placement {
                part: "3005.dat".into(),
                color: 15,
                translation_ldu: [5.0, 1.0, 0.0],
                matrix: Orientation::IDENTITY.matrix(),
                declared_off_grid: false,
                build_step: 0,
            },
            Placement {
                part: "3005.dat".into(),
                color: 15,
                translation_ldu: [0.0, 40.0, 0.0], // off the ground and unsupported
                matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.5, 0.0, 0.0, 1.0], // not a real rotation
                declared_off_grid: false,
                build_step: 0,
            },
        ];
        let problems = validate(&placements, &FootprintTable::standard());
        assert!(problems.iter().any(|p| matches!(p, Illegality::OffGridTranslation { axis: 'x', .. })));
        assert!(problems.iter().any(|p| matches!(p, Illegality::OffGridTranslation { axis: 'y', .. })));
        assert!(problems.iter().any(|p| matches!(p, Illegality::NonAxisRotation { .. })));
        assert!(problems.iter().any(|p| matches!(p, Illegality::Floating { .. })));
    }

    #[test]
    fn validate_accepts_two_bricks_stacked_directly_with_no_illegality() {
        // LDraw's Y axis points down (see `ldraw-scenes/monolith.ldr`'s own
        // comment), so the base course's translation is *negative* one
        // brick height: its physical bottom (translation + height) is
        // exactly the ground plane, y=0. The second course goes one more
        // brick height up (more negative).
        let base = Placement::on_grid(GridPos::new(0, -(BRICK_PLATES as i32), 0), Orientation::IDENTITY, "3005.dat", 15);
        let stacked = Placement::on_grid(GridPos::new(0, -(2 * BRICK_PLATES as i32), 0), Orientation::IDENTITY, "3005.dat", 15);
        let problems = validate(&[base, stacked], &FootprintTable::standard());
        assert_eq!(problems, vec![]);
    }

    #[test]
    fn validate_flags_two_bricks_placed_on_top_of_each_other_at_the_same_height_as_overlap() {
        let a = Placement::on_grid(GridPos::new(0, 0, 0), Orientation::IDENTITY, "3005.dat", 15);
        let b = Placement::on_grid(GridPos::new(0, 0, 0), Orientation::IDENTITY, "3005.dat", 4);
        let problems = validate(&[a, b], &FootprintTable::standard());
        assert!(problems.iter().any(|p| matches!(p, Illegality::Overlap { .. })));
    }

    #[test]
    fn validate_flags_a_brick_floating_above_the_ground_with_nothing_under_it() {
        // One brick height short of resting on the ground, and nothing below it.
        let floating = Placement::on_grid(GridPos::new(0, -(2 * BRICK_PLATES as i32), 0), Orientation::IDENTITY, "3005.dat", 15);
        let problems = validate(&[floating], &FootprintTable::standard());
        assert!(problems.iter().any(|p| matches!(p, Illegality::Floating { .. })));
    }

    #[test]
    fn nearest_yaw_snaps_to_one_of_the_four_pure_yaw_orientations() {
        let o = Orientation::nearest_yaw(88.0);
        let m = o.matrix();
        // Should land on the ~90-degree yaw member, not identity.
        assert!((m[4] - 1.0).abs() < 1e-9);
        assert_ne!(o, Orientation::IDENTITY);
    }
}
